

# Eureka Discovery Client Properties
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9095/eureka
  instance:
    prefer-ip-address: true

spring:
  application:
    name: configserver
# Spring config server properties
  cloud:
    config:
      server:
        git:
          uri: https://github.com/bvm-arjun108/SoccerApplication
          clone-on-start: true


server:
  port: 9097


