spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: soccerdb


  application:
    name: ratingapplication

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

server:
  port: 9094

# Eureka Discovery Client Properties
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9095/eureka
  instance:
    prefer-ip-address: true
