package com.app.LeagueApplication.model;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import com.fasterxml.jackson.annotation.JsonInclude;
import jakarta.persistence.Transient;
import lombok.*;

import java.util.List;

// Dynamodb does not create the table automatically. So, we need to create it manually.
@Data
@AllArgsConstructor
@NoArgsConstructor
@DynamoDBTable(tableName = "league")
public class League {
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id;
    @DynamoDBAttribute // The mapping between the DynamoDb
    private String leagueName;
    @DynamoDBAttribute
    @JsonInclude(JsonInclude.Include.NON_NULL)
    private Address address;
    @DynamoDBAttribute
    @Transient // We don't want to save the rating in the database
    private List<Rating> ratings;

}
